version: 2.1

jobs:
  process-gradle-build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: 'build'
          command: './gradlew build'

workflows:
  build-app:
    jobs:
      - process-gradle-build
